version: '3'
services: 
  api: 
    build: 
      context: ./PythonAPI
    container_name: api
    image: public.ecr.aws/j5g4t9t6/python_api
    ports: 
      - "5000:5000"
  ui: 
    build: 
      context: ./FE
    container_name: ui
    image: public.ecr.aws/j5g4t9t6/angular_ui
    ports: 
      - "4200:4200"
  